### ISSUE TITLE
iBright

### ISSUE THREAD

**Issue by GoDzM4TT3O** [Pythonista-Tools/Pythonista-Tools#100]
Name of Script: iBright
Short Description: Change the brightness of your device!
URL: https://github.com/GoDzM4TT3O/iBright
Category: 10 lines or less

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by tjferry14** [comment]
Added. Thank you!
