### ISSUE TITLE
iHashIt

### ISSUE THREAD

**Issue by GoDzM4TT3O** [Pythonista-Tools/Pythonista-Tools#103]
Name of Script: iHashIt
Short Description: Hash a string from user-input!
URL: https://github.com/GoDzM4TT3O/iHashIt
Category: Utilities (Fun? You decide! ;] )

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by tjferry14** [comment]
Added. Thank you!
