### ISSUE TITLE
iLiveStats

### ISSUE THREAD

**Issue by GoDzM4TT3O** [Pythonista-Tools/Pythonista-Tools#105]
Name of Script: iLiveStats
Short Description: Check if a user is live on YouTube and print details
URL: https://github.com/GoDzM4TT3O/iLiveStats
Category: Utilities

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by tjferry14** [comment]
Added. Thank you!
