### ISSUE TITLE
DownloadRedditComments

### ISSUE THREAD

**Issue by GoDzM4TT3O** [Pythonista-Tools/Pythonista-Tools#106]
Name of Script: DRC
Short Description: Download Reddit Comments & save to file
URL: https://github.com/GoDzM4TT3O/DRC
Category: fun AND tools

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by cclauss** [comment]
This script needs work before we can accept it.  In Pythonista, can you please run PyFlakes and check style against it and fix the issues?

**Comment by cclauss** [comment]
Also if you are going to submit lots of small scripts the perhaps it would be better to put them all in one repo and then you are free to add, modify, delete at will.  This is the approach that I took with https://github.com/cclauss/Ten-lines-or-less

**Comment by cclauss** [comment]
The name DRC is not very Pythonic.  Could you please consider a name that is more self explanatory?

**Comment by GoDzM4TT3O** [comment]
@cclauss The script does indeed work on Pythonista, and I also made a Repo containing my Pythonista scripts. Also, I don’t really know what to name it, since it stands for Download Reddit Comments

**Comment by GoDzM4TT3O** [comment]
@cclauss [Here](https://share.icloud.com/photos/0yRqptHCxa-2Ke8yzXhjabp6A) I created a short video, just to show that it works fine for me. Though it was hard for me to hanfle the Unicode characters, because, if there are any characters, the program would throw an error. Now it no longer should. Though, the comment body always has a ‘b’ before it (example: b’insert comment here’). I don’t know how to fix that. I worked on this program for one day and a half.

**Comment by GoDzM4TT3O** [comment]
Also, my script collection can be found [here](https://github.com/GoDzM4TT3O/Pythonista)

**Comment by GoDzM4TT3O** [comment]
After working on it for an hour, I fixed it! Publishing the updated code now!

**Comment by GoDzM4TT3O** [comment]
The code now works, and, thanks to cclauss, even shorter and effective!
