### ISSUE TITLE
Free Pythonista apps

### ISSUE THREAD

**Issue by alanjohnedwards** [Pythonista-Tools/Pythonista-Tools#108]
Name of Script:aPlan sp
Short Description:aPlan sp is a magazine flatplanning tool written in Pythonista 3 on and for iPad. 
URL:https://itunes.apple.com/gb/app/aplan-sp/id1453002135?mt=8
Category:Productivity

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by cclauss** [comment]
Done.  https://github.com/Pythonista-Tools/Pythonista-Tools/blob/master/Pythonista%20Apps%20in%20the%20Apple%20AppStore.md

It looks really cool.  Congratulations 🎉
