### ISSUE TITLE
IOS App Building

### ISSUE THREAD

**Issue by quantumquark07** [Pythonista-Tools/Pythonista-Tools#129]
I see there is a list of apps that have been published with PyhonIsta, some paid.   However the apps don't appear to be available in my region (USA).

Does this mean that in other countries apple is allowing pythonista built apps to be independent apps ?  What is the process for making them independent is there online documentation?

**Comment by cclauss** [comment]
Good question.  Please re-post it on https://github.com/omz/Pythonista-Issues and https://forum.omz-software.com so we can see what others think.
