### ISSUE TITLE
New link and question

### ISSUE THREAD

**Issue by 671620616** [Pythonista-Tools/Pythonista-Tools#35]
Hi everyone,
Firstly, I have a [file] [] that I'd like to add to the Utilities section.  However, I am now aware of the website, but am not good with HTML and don't want to mess something up on the website.  My question -- what is/is there a procedure on adding a gist?
Thanks!

[file]: https://gist.github.com/671620616/6ce321b939dfc23797a3

**Comment by Gerzer** [comment]
Just open an issue and someone will handle adding it to the website. Just do what you just did. ;-)

**Comment by Gerzer** [comment]
Done.
