### ISSUE TITLE
Add link to website

### ISSUE THREAD

**Issue by 671620616** [Pythonista-Tools/Pythonista-Tools#36]
I've added [this file] [] to the Utilities.md file but not to the website -- while I'm still getting used to how GitHub works, could someone do this for me so I don't mess something up?  Thanks!

[this file]: https://gist.github.com/671620616/0728664ccf51b9b2bcce

**Comment by tjferry14** [comment]
Will do when I get home. I'm pondering if there is a way to automatically do this.
