### ISSUE TITLE
Please add instructions to get scripts from here to Pythonista running on an iPad

### ISSUE THREAD

**Issue by steb** [Pythonista-Tools/Pythonista-Tools#39]
URL:

**Comment by Gerzer** [comment]
Pythonista Tools is currently just a collection of links to different projects made in Pythonista, so if there is something you want to download, go to its link and follow the instructions the project itself provides. If no instructions can be found at the project’s homepage, try asking about it on the [Pythonista forums](http://omz-forums.appspot.com/pythonista).

**Comment by tjferry14** [comment]
+1 on @Gerzer's answer.

**Comment by tjferry14** [comment]
@Gerzer I also added your answer to the projects readme.

**Comment by Gerzer** [comment]
Ok, great!

**Comment by 671620616** [comment]
If I were to go about making a download script (for use in Pythonista), would it be wiser to use the download links from the GitHub repo or the site?
