### ISSUE TITLE
Github Tools Section

### ISSUE THREAD

**Issue by tjferry14** [Pythonista-Tools/Pythonista-Tools#48]
I think we're getting to a point where there are so many Github tools in utilities, that we MIGHT need a section separate for them.

**Comment by cclauss** [comment]
What is the distinction between a tool and a utility?

What about GitHub tools vs. Utilities instead?

**Comment by tjferry14** [comment]
I just wanted to clean it up a little.

**Comment by cclauss** [comment]
Understood ...  It is just that the Repo is called Pythonista-Tools so it is a bit wierd to have a Tools section with most of the items in the repo NOT being in the Tools section.  Spring cleaning is a great idea.

**Comment by tjferry14** [comment]
I guess we misunderstood each other, I was suggesting a section called "GitHub tools" for scripts primarily based on downloading repos & gists from GitHub and Gist

**Comment by cclauss** [comment]
That makes good sense to me.
