### ISSUE TITLE
Repo request

### ISSUE THREAD

**Issue by MCS-Kaijin** [Pythonista-Tools/Pythonista-Tools#60]
Please add EsolangsInerpreter (http://www.github.com/MCS-Kaijin/EsolangsInterpreter). I'm not sure which category you want it in, but it is a "utility" that possesses no real practical use which makes it more for entertainment though it's not really a game. What it is, however, is an interpreter for esoteric programming languages that currently supports two languages.

**Comment by tjferry14** [comment]
Done. Thank You!
