### ISSUE TITLE
My Pythonista apps

### ISSUE THREAD

**Issue by marcus67** [Pythonista-Tools/Pythonista-Tools#63]
https://github.com/marcus67/gitsynchista - gitsynchista - Pythonista tool to synchronize local files with a Github repository hosted on a WebDav server

https://github.com/marcus67/pyzipista - pyzipista - Tool to create a self-extracting Pythonista application

https://github.com/marcus67/rechtschreibung - rechtschreibung - A little Python app to test different rule sets for German spelling

**Comment by tjferry14** [comment]
Done. Thank you!

**Comment by cclauss** [comment]
I would think that gitsynchista goes in the GitHub tools section instead of Utilities.

**Comment by tjferry14** [comment]
@cclauss My mistake. Will fix.

**Comment by tjferry14** [comment]
Fixed.
