### ISSUE TITLE
Please add this link to Pythonista-Tools

### ISSUE THREAD

**Issue by ShunSakurai** [Pythonista-Tools/Pythonista-Tools#71]
Name of Script: Password Generator
Short Description:  A simple password generator that lets the user copy the generated password to the clipboard with a single tap
URL: https://github.com/ShunSakurai/password_generator
URL regarding the Pythonista code is only: https://github.com/ShunSakurai/password_generator/blob/master/password_iphone.py
Category: Utility

The desktop version is finished, but iPhone is only a beta version. I am planning to add a functionality to change the number and the length of the generated passwords.

**Comment by tjferry14** [comment]
Added. Thank you!
