### ISSUE TITLE
Add new "fun" category

### ISSUE THREAD

**Issue by Ivoah** [Pythonista-Tools/Pythonista-Tools#74]
I made a program for browsing XKCD comics, and it doesn't really seem to fit in any pre-existing category. I think something like a "fun" category would be fitting for something that isn't a game, but doesn't fit anywhere else. Even an "other" category would be good.

**Comment by Ivoah** [comment]
I added an "other" category.

**Comment by cclauss** [comment]
Personally, I find `fun` to be more descriptive and helpful that `other`.  The latter merely pushes the job of catigorization from the submitter/maintainer to the user.  Forcing the contributor to think about how users would catigorize their work is a good thing.  It is too easy for `other` to just become the place where users check last if ever.

**Comment by Gerzer** [comment]
I agree

**Comment by Ivoah** [comment]
You're right about `other` not being the best category name. I don't really think `fun` is a very descriptive name either, especially as we already have a `games` category.

**Comment by Gerzer** [comment]
Maybe "entertainment"?

**Comment by tjferry14** [comment]
We should all agree on a category name before closing the issue ;).

+1 for `Fun`

**Comment by cclauss** [comment]
I think `fun` is descriptive.  I take it to mean that the script should not be too serious (e.g., not a `utility`) and it is not a `game` but is still might be a hoot to download.  For me, a game can be considered `entertainment` so that is less helpful.  Besides... Fun is just fun!!

**Comment by Ivoah** [comment]
Actually, yeah, as @cclauss said `fun` would probably work well. My vote is for `fun` :)

**Comment by tjferry14** [comment]
All votes for fun? :)

**Comment by streathamhill** [comment]
+1

**Comment by Ivoah** [comment]
So it seems we're all agreed on `fun`, shall I close the thread and change it?

**Comment by tjferry14** [comment]
Go ahead!
