### ISSUE TITLE
Update button

### ISSUE THREAD

**Issue by Ivoah** [Pythonista-Tools/Pythonista-Tools#75]
I think there should be an update button. Currently the only way to update a script is to delete it and reinstall it. This is slightly counterintuitive. Maybe if a script is installed there would be two buttons, `update` and `delete`.

**Comment by tjferry14** [comment]
Not sure what you mean by this. Are you referring to the Pythonista app itself?

**Comment by Gerzer** [comment]
I think he's talking about the downloader.

**Comment by Ivoah** [comment]
Yes, I'm talking about the downloader.

**Comment by tjferry14** [comment]
@Ivoah Please create an issue on that repo. https://github.com/ywangd/pythonista-tools-installer

**Comment by Ivoah** [comment]
Ah, sorry about that.
