### ISSUE TITLE
Access to spreadsheet

### ISSUE THREAD

**Issue by Gerzer** [Pythonista-Tools/Pythonista-Tools#77]
Is there any way I and other Pythonista Tools admins/devs can gain access to the backend spreadsheet? I know I haven't been active recently but I want to help out again. I understand if you want to keep access tightly controlled, however.

**Comment by tjferry14** [comment]
Sure. Just give me your email address and I will certainly share access, however we should try our best to keep it in sync with the repo markdown files and somewhat tightly controlled.

**Comment by Gerzer** [comment]
I completely agree and will never give anyone else access without your approval first. My email address is gerzer.net@gmail.com. Thanks!

**Comment by Ivoah** [comment]
Wait, what backend spreadsheet?

**Comment by tjferry14** [comment]
@Gerzer Invite Sent

@Ivoah There is a backend spreadsheet that powers the website side of things.

**Comment by Gerzer** [comment]
Thanks!
