### ISSUE TITLE
Dropbox File Picker script compatible with Python 3

### ISSUE THREAD

**Issue by zmitchell** [Pythonista-Tools/Pythonista-Tools#79]
Name of Script: Dropbox File Picker 
Short Description: A script to enable Pythonista to download files from Dropbox
URL: https://github.com/zmitchell/Pythonista-Dropbox-Picker
Category: Utilities

**Comment by cclauss** [comment]
@omz Are you OK with this fork going out under a GNU license?  Do you have a preference?

**Comment by omz** [comment]
@cclaus I'd prefer a more liberal license, like MIT/BSD or CC0. In this particular case, it's unlikely to matter, but a GNU license would prevent me from including the code in Pythonista.

**Comment by cclauss** [comment]
@zmitchell Would you consider making a license change?

**Comment by zmitchell** [comment]
Yeah, I can do that. I just chose a license for the sake of choosing a license. I'll change it to MIT.
