### ISSUE TITLE
Remote-controllable digital image frame with built-in web server

### ISSUE THREAD

**Issue by SpotlightKid** [Pythonista-Tools/Pythonista-Tools#83]
Name of Script: ImageFrame.py
Short Description: Remote-controllable digital image frame with built-in web server
URL: http://tinyurl.com/iosimageframe (https://gist.github.com/SpotlightKid/be9bc4c08a9e1531287c89182f7931d8)
Category: Graphics and Imaging

Forum post: https://forum.omz-software.com/topic/3781/script-remote-controllable-digital-image-frame

**Comment by tjferry14** [comment]
Added. Thank you!
