### ISSUE TITLE
Activate backup of iCloud

### ISSUE THREAD

**Issue by enichols22124** [Pythonista-Tools/Pythonista-Tools#85]
Name of Script: runbackuptoicloud
Short Description: Start a backup of the IOS phone/tablet to iCloud, presuming icloud account already exists. Would prefer this run in the background without notification. Can be a button that one presses or on a timer to run every time period selected, from 1 hour to 24 hours. 
URL: ?
Category: backup

**Comment by tjferry14** [comment]
This repo isn't for Pythonista feature requests. Thank you.
