### ISSUE TITLE
Bob and Angie game

### ISSUE THREAD

**Issue by Evan03Davis** [Pythonista-Tools/Pythonista-Tools#86]
Name of Script: Bob and Angie 
Short Description: Platformer like game
URL: https://github.com/TutorialDoctor/Pythonista-Projects/tree/master/Projects/Games/Game%20Engine
Category: Games

**Comment by tjferry14** [comment]
I personally believe this should be under utilities as a game engine, rather than just the demo game. Do you agree?

**Comment by Evan03Davis** [comment]
After looking at it a bit more, I agree. It's more for helping rather than a standalone demo. Thanks

**Comment by tjferry14** [comment]
Added. Thank you!

**Comment by Evan03Davis** [comment]
Thanks very much, I tried to install it just now and it says "Installation failed" just thought I'd let you know. Evan
