### ISSUE TITLE
My .py script can't find its .pyui view,  when launched from home screen

### ISSUE THREAD

**Issue by whearst3** [Pythonista-Tools/Pythonista-Tools#87]
Name of Script:

Short Description: Both the .py and its associated .pyui are in the same folder on my iOS device. And the .py script runs fine.  When it encounters  ui.load.view('myui') from inside Pythonista environment, the .pyui view loads ... all is well. 

But,  when I run this script from an icon on the iPhone home screen. It hangs with a message about < can't find my.pyui file >.   

So I assume that when Pythionista loads "cold" it doesn't know where to find the associated .pyui file. Should I put it into a default directory?   Which one?  Or is there some way to indicate the path to search for .pyui files at runtime?

URL:
Category: pyui

**Comment by tjferry14** [comment]
This repo isn't for Pythonista issues. Please head over to https://github.com/omz/Pythonista-Issues to open an issue there. Thank you.

**Comment by whearst3** [comment]
Ok


--------

**Comment by omz** [comment]
@whearst3 I'd also appreciate if you could re-post this in the [Pythonista bug tracker](https://github.com/omz/Pythonista-Issues/issues). This does seem like a bug to me – for a quick workaround, you could add something like this at the beginning of your script:

```python
import os
os.chdir(os.path.split(__file__)[0])
```

**Comment by whearst3** [comment]
Re-posted to 'bug tracker'  ... and thanks for the workaround suggestion.

**Comment by whearst3** [comment]
thanks that workaround  suggested  a good fix. - Will
