### ISSUE TITLE
AWS Lambda deployer

### ISSUE THREAD

**Issue by mikaelho** [Pythonista-Tools/Pythonista-Tools#88]
Name of Script: lambda-deploy
Short Description: Utility that deploys a Python function as an Amazon Web Services serverless Lambda function, complete with an API endpoint (url). You can return JSON or HTML.
URL: https://github.com/mikaelho/pythonista-lambda-deploy
Category: Internet of Things or Utilities

**Comment by tjferry14** [comment]
@cclauss Would you think this would go under Internet of Things?

**Comment by mikaelho** [comment]
As a new admin, I suggest instead of act:

Would it make sense to establish a "Cloud services" category, which would contain things related to Dropbox, Google services, AWS, Azure etc.?

**Comment by tjferry14** [comment]
Added. Thank you!
