### ISSUE TITLE
Why the extra [] after the filenames?

### ISSUE THREAD

**Issue by cclauss** [Pythonista-Tools/Pythonista-Tools#89]
https://github.com/Pythonista-Tools/Pythonista-Tools/blob/master/Utilities.md  See `editmenu`.

**Comment by lukaskollmer** [comment]
These are just broken markdown links. If you look at the raw md file, you see that some rows have no space between the link name and the brackets: `[StaSh][]`.
The rows with the extra `[]` after the filename have an extra space between the link name and the brackets: `[editmenu] []`. 

You should be able to fix this by removing the extra spaces

**Comment by tjferry14** [comment]
I believe something changed in the GitHub link markdown, as these were never there before recently. Will fix.
