### ISSUE TITLE
Add PyDoc

### ISSUE THREAD

**Issue by shaun-h** [Pythonista-Tools/Pythonista-Tools#92]
Name of Script: PyDoc
Short Description:  A docset browser written for Pythonista 
URL: https://github.com/shaun-h/pydoc
Category: Utilities

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by shaun-h** [comment]
I have added this to the Utilites.md but need to get the website updated with it.

**Comment by tjferry14** [comment]
Done. Thank you!
