### ISSUE TITLE
Dropbox File Picker V2

### ISSUE THREAD

**Issue by encela95dus** [Pythonista-Tools/Pythonista-Tools#93]
Name of Script:Dropbox File Picker V2.py
Short Description: omz's script of the similar name enhanced to support dropbox version 2 
See the discussion at https://forum.omz-software.com/topic/4425/dropbox-file-picker-needs-update
URL:https://gist.github.com/encela95dus/67fd65aec0c25336ac8e70153ebcf7eb
Category:utilities

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by tjferry14** [comment]
Added. Thank you! Also, see here for an alternate script: https://github.com/zmitchell/Pythonista-Dropbox-Picker

**Comment by mikaelho** [comment]
@tjferry14, did you have time to check that the alternative you linked to works with Dropbox API v2?

**Comment by tjferry14** [comment]
@mikaelho I did not actually. Just assumed from the description.
