### ISSUE TITLE
New app I made with Pythonista

### ISSUE THREAD

**Issue by Maxmad68** [Pythonista-Tools/Pythonista-Tools#94]
**Name of app:** QNH

**Short Description:** QNH 's purpose is to give essential informations to pilots, like the weather report (METAR) or airports informations (NOTAM, informations about runways and radios...)

**URL:** https://itunes.apple.com/us/app/qnh/id1218922617?l=fr&ls=1&mt=8

**Category:** Sport, Travel

I'm a 15 years old french student and I spent a lot of time in making this app.
I propose it for 1,99$ on the AppStore.
I saw the list with all apps that have been made with Pythonista and I'd like to try adding mine to this list ;-)
Thank you,
M.Madrau

**Comment by tjferry14** [comment]
Added. Thank you!
