### ISSUE TITLE
Neuroscience game 

### ISSUE THREAD

**Issue by yueqiw** [Pythonista-Tools/Pythonista-Tools#95]
Name of Script: Neuron I/O
Short Description: a Pythonista game of neuronal activity recordings in the brain
URL: https://github.com/yueqiw/ophys-game-ios
Category: Games

Thanks! 

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by tjferry14** [comment]
Added. Thank you!

**Comment by yueqiw** [comment]
Thanks! 
I found that when I download the game, it's placed in the directory `Games/Neuron I/O` with the `/` creating a subfolder `/O` under `Games/Neuron I`. Could you change it to something like `Neuron IO` ? Thanks!

**Comment by tjferry14** [comment]
Thanks for pointing that out. I have changed the name.

**Comment by yueqiw** [comment]
Thanks!
