### ISSUE TITLE
cNotif - custom notification for Pythonista

### ISSUE THREAD

**Issue by GoDzM4TT3O** [Pythonista-Tools/Pythonista-Tools#97]
Name of Script: cNotif
Short Description: cNotif - Custom Notification for Pythonista - Send custom text and open an app with its x-callback-url in order to make the notification appear at the top of the screen. You will have to wait 15 seconds before the notification will be sent.
URL: https://github.com/GoDzM4TT3O/cNotif
Category: Fun

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by tjferry14** [comment]
Added. Thank you!
