### ISSUE TITLE
iEditor

### ISSUE THREAD

**Issue by GoDzM4TT3O** [Pythonista-Tools/Pythonista-Tools#98]
Name of Script: iEditor
Short Description: Simple Pythonista script that creates a new file, alongside its extension (provided by the user), and automatically creates a template for the user (example: html)
URL: https://github.com/GoDzM4TT3O/iEditor
Category: Utilities

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by tjferry14** [comment]
Added. Thank you!
