### ISSUE TITLE
iServer

### ISSUE THREAD

**Issue by GoDzM4TT3O** [Pythonista-Tools/Pythonista-Tools#99]
Name of Script: iServer
Short Description: iServer is a script made for Pythonista 3 by GoDzM4TT3O on 18 August 2018. It starts a server (by default) on port 80.
URL: https://github.com/GoDzM4TT3O/iServer/
Category: Utilities

**Note: Pythonista Tools is NOT the repo for Pythonista. Issues with Pythonista should be brought up on the Pythonista Issue Tracker repo, found [here](https://github.com/omz/Pythonista-Issues).**

**Comment by tjferry14** [comment]
Added. Thank you!
